In [2]:
!pip install numpy

In [4]:
import numpy as np


In [5]:
a = np.array([1,2,3,"a",{1:2}])

In [7]:
a

array(10)

In [6]:
a = np.array(10)
b = np.array([1,2,3])
c = np.array([[1,2,3], [4,5,6]])
d = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])

In [8]:
print('a dimension :', a.ndim)
print('b dimension :', b.ndim)
print('c dimension :', c.ndim)
print('d dimension :', d.ndim)

a dimension : 0
b dimension : 1
c dimension : 2
d dimension : 3


In [9]:
print(a)
print('shape of a:', a.shape)
print(b)
print('shape of b:', b.shape)
print(c)
print('shape of c:', c.shape)
print(d)
print('shape of d:', d.shape)

10
shape of a: ()
[1 2 3]
shape of b: (3,)
[[1 2 3]
 [4 5 6]]
shape of c: (2, 3)
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
shape of d: (2, 2, 3)


In [10]:
c.dtype
d.dtype

dtype('int64')

In [11]:
type(a)
type(b)
type(c)
type(d)

numpy.ndarray

In [12]:
len(b)

3

In [13]:
#create a numpy array using arange with 1 and 11 as parameter in it
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
#using start, stop, step
np.arange(1,12,2)

array([ 1,  3,  5,  7,  9, 11])

In [15]:
# Eye function
np.eye(5,dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [16]:
#Creating a numpy array using Zero function with(3,2) as passed parameter takes default float
np.zeros((5,5),dtype= 'int')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

using ones function


In [17]:
np.ones((5,5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

USING FULLS FUNCTION

In [18]:
np.full((5,5),8,dtype=int)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

USING DIAG FUNCTION

In [19]:
x = [1,2,3,4,5]
np.diag(x)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

**NUMPY RESHAPE**:
RESHAPE MEANS CHANGING THE SHAPE OF AN ARRAY


In [28]:
# Reshape functon:reshaping means changing the shape of an array,
# the shape of an array is the number of elements in each dimension.
# Using arange() to generate numpy array x with numbers between 1 to 15
x = np.arange(1, 19)
print(x)
print(x.shape)
print(x.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
(18,)
1


In [30]:
# Reshape x with  3 rows and 6 columns
n=x.reshape((3,6))
print(n)
print(n.shape)
print(n.ndim)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
(3, 6)
2


In [32]:
n1=n.reshape((3,6,1))
print(n1)
print(n1.shape)
print(n1.ndim)


[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]
  [10]
  [11]
  [12]]

 [[13]
  [14]
  [15]
  [16]
  [17]
  [18]]]
(3, 6, 1)
3


In [34]:
#ravel
# convert to old dimension
v=n.ravel()
print(v.shape)
print(v)
print(v.ndim)

(18,)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
1


In [36]:
# Flattening x convert array into one dimensional
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18])

In [38]:
#Numpy array indexing
# Create an array a with all even numbers between 1 to 14
a = np.arange(2,14,2)

# print a
a

array([ 2,  4,  6,  8, 10, 12])

In [40]:
# Get third element in array a
print(a[2])

6


In [42]:
#Print 1st, 3rd, 5th, and 7th element in array a
# a[0:7:2]
a[2:5]

array([ 6,  8, 10])

In [44]:
# Define an array b again with [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]] as its elements.
b = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
b.shape
b

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [46]:
# Print 3rd element from 2nd list which is 1st list in nested list passed. Confusing right? 'a' have nested array.Understand the braket differences.
print(b[1][1][1])

11


In [48]:
#Numpy Array Slicing : slicing in python means taking elements from one given index to another given index.
#Array slicing in 1-d array
arr=np.arange(1,14)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [50]:
# Slice elements from 1st to 8th element from array arr:
arr[1:8]

array([2, 3, 4, 5, 6, 7, 8])

In [51]:
# Slice elements from index 4 to the end of the array arr:
arr[4:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13])

In [52]:
# Slice elements from the beginning to index 7 (not included) in array arr:
arr[:7]

array([1, 2, 3, 4, 5, 6, 7])

In [54]:
# Print every other element from index 1 to index 7:
arr[1:10:2]

array([ 2,  4,  6,  8, 10])

In [56]:
# Return every other element from the entire array arr:
arr[0:10:2]

array([1, 3, 5, 7, 9])

In [58]:
#Numpy copy as view

x1= np.arange(18)
x1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [61]:
# assign x2 = x1
x2 = x1

In [63]:
print(x1)
print(x2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [65]:
x2[0] = 10

In [67]:
print(x1)
print(x2)

[10  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
[10  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


In [75]:
#apply conditions
a

array([ 2,  4,  6,  8, 10, 12])

In [77]:
# Check if every element in array a greater than 3 or not Using '>' notation
a > 4

array([False, False,  True,  True,  True,  True])

In [79]:
# Get a list with all elements of array 'a' greater than 3 but less than 6
a[(a > 2) & (a <= 6)]


array([4, 6])

In [82]:
#mathematical operations
#defining a
import numpy as np
a= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [84]:
# print trigonometric sin value of each element of a
np.sin(a)


array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [85]:
# print total sum of elements of a
np.sum(a)

np.int64(45)

In [86]:
# print median of array a
print(np.median(a))

5.0


In [87]:
# print mean of array a
print(np.mean(a))

5.0


In [88]:
#standard deviation
# print standard deviation of array a
np.std(a)

np.float64(2.581988897471611)